version: '3.8'

services:
  db:
    build: .
    ports:
      - "54323:54323"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata

volumes:
  postgres_data: 